trigger:
  branches:
    include:
      - main  # You can change this to any branch you want to monitor

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Set up Python environment and install dependencies'

  - script: |
      source venv/bin/activate
      python -m unittest discover tests
    displayName: 'Run Unit Tests'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results.xml'
      failTaskOnMissingResultsFile: false
      testRunTitle: 'Python Unit Tests'
