trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Step 1: Set up Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# Step 2: Install dependencies
- script: |
    python -m venv venv
    source venv/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
    pip install unittest-xml-reporting
  displayName: 'Install dependencies'


    
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'RupeshAzureConnection'         # Use the exact name you saved
    appName: 'samplepythonapprupesh'
    package: '$(System.DefaultWorkingDirectory)'
